import BuildingCinema from "../building/buildingCinema.js";
import BuildingComercialCenter from "../building/buildingComercialCenter.js";
import BuildingFactory from "../building/buildingFactory.js";
import BuildingHospital from "../building/buildingHospital.js";
import BuildingHotel from "../building/buildingHotel.js";
import BuildingHouse from "../building/buildingHouse.js";
import BuildingPark from "../building/buildingPark.js";

export default class District {
    constructor(name, desc, population,populationIncrease, satisfaction, moneyGenerated,
        district_building ,buildings, space_building, 
        is_special_built, special_building, 
        PNGwithOutSpecial, PNGwithSpecial, posX, posY) {

        this.name = name;                                                                                       // Name of the district
        this.desc = desc;                                                                                       // Description of the district                              
        this.population = population;                                                                           // Population of the district    
        this.populationIncrease = populationIncrease;                                                           // Population increase of the district
        this.satisfaction = satisfaction;                                                                       // Satisfaction of the population in the district
        this.baseSatisfaction = satisfaction;                                                                   // Base satisfaction of the district, used to calculate the satisfaction after modifying the district percentage
        this.moneyGenerated = moneyGenerated;                                                                   // Money generated by the district per cycle
        this.moneyGeneratedByBuildings = [];                                                                    // Money generated by the buildings in the district per cycle
        this.baseMoneyGenerated = moneyGenerated;                                                               // Base money generated by the district, used to calculate the money generated after modifying the district percentage
        this.baseMoneyGeneratedByBuildings = [];                                                                // Base money generated by the buildings in the district, used to calculate the money generated by buildings after modifying the district percentage
        this.district_building = this.createBuildings(this.built = false,district_building);                    // District building that can be built in the district
        this.building_list = this.createBuildings(this.built = true,buildings);                                 // List of buildings built in the district
        this.space_building = space_building;                                                                   // Space where buildings its posible in the district
        this.is_special_built = is_special_built;                                                               // Is the special building built in this district
        this.special_building = special_building;                                                               // Special building that can be built in the district
        this.PNGwithOutSpecial = PNGwithOutSpecial;                                                             // PNG of the district without the special building
        this.PNGwithSpecial = PNGwithSpecial;                                                                   // PNG of the district with the special building         
        this.scene_list = this.createSceneList();                                                               // List of scenes for each districtScene
        this.posX = posX;                                                                                       // Position X of the district in the map
        this.posY = posY;                                                                                       // Position Y of the district in the map
        this.taxes = 50;                                                                                        // Percentage 0-100
        this.security = 50;
        this.workSchedule = 50;
        this.cleaning = 50;
    }
    // UPDATE DATA
    updateDistrict() {
        this.updatePopulation(this.populationIncrease);
        return this.getMoneyGenerated();
    }
    // ASSETS
    spawnDistrict(scene){
        this.texture = this.is_special_built ? this.PNGwithSpecial : this.PNGwithOutSpecial;
        const button = scene.add.image(this.posX, this.posY, this.texture).setOrigin(0).setScale(1)
            .setInteractive({
                useHandCursor: true,
                pixelPerfect: true
            });
        const outline = scene.add.graphics();
        outline.lineStyle(3, 0xcccccc, 1);
        outline.setDepth(10);
        outline.setPosition(-5, -10);
        if(this.polygonPts && this.polygonPts.length > 0){
            outline.beginPath();
            outline.moveTo(this.polygonPts[0].x, this.polygonPts[0].y);
            for(let i = 1; i < this.polygonPts.length; i++)
                outline.lineTo(this.polygonPts[i].x, this.polygonPts[i].y);
            outline.closePath();
            outline.strokePath();
        }
        outline.setVisible(false);
        button.on('pointerover', () => {outline.setVisible(true);});
        button.on('pointerout', () => {outline.setVisible(false);});
        button.on('pointerup', () => {
            scene.updateDistrictFooter(this);
            scene.scene.pause('gameScene');
            scene.scene.launch('districtScene', { district: this});
        });
        return button;
    }
    getPNGwithOutSpecial() {return this.PNGwithOutSpecial;}
    getPNGwithSpecial() {return this.PNGwithSpecial;}
    // SCENES
    getSceneList() {return this.scene_list}
    createSceneList(){throw new Error('createSceneList() debe implementarse en la subclase');}
    
    getName() {return this.name;}
    getDescription() {return this.desc;}
    //getPosX() {return this.posX;}
    //getPosY() {return this.posY;}

    //POPULATION
    getPopulation() {return this.population;}
    updatePopulation(value) {this.population = Math.max(0, this.population + value);}
    updatePopulationIncrease(value){this.populationIncrease = Math.max(0, this.populationIncrease + value);}
    getPopulationIncrease() {return this.populationIncrease;}

    // MODIFYING DISTRICT MONEY AND SATISFACTION BY FOOTER ATTRIBUTES, 50 IS THE BASE
    updateAfterModifyPercentage(){  
        this.modifyDistrictMoneyGenerated(); 
        this.modifyDistrictSatisfaction();  
    }
    //SATISFACTION
    getSatisfaction() {return this.satisfaction;}
    updateSatisfaction(value){
        this.satisfaction = Math.max(0, Math.min(100, this.satisfaction + value));
        this.baseSatisfaction = Math.max(0, Math.min(100, this.baseSatisfaction + value));
    }
    modifyDistrictSatisfaction(){
        // IF TAXES INCREASE, SATISFACTION DECREASES. IF TAXES DECREASE, SATISFACTION INCREASES
        // IF SECURITY INCREASE, SATISFACTION INCREASES. IF SECURITY DECREASE, SATISFACTION DECREASES
        // IF WORK SCHEDULE INCREASE, SATISFACTION DECREASES. IF WORK SCHEDULE DECREASE, SATISFACTION INCREASES
        // IF CLEANING INCREASE, SATISFACTION INCREASES. IF CLEANING DECREASE, SATISFACTION DECREASES
        this.satisfaction = this.baseSatisfaction;
        if(this.taxes > 50) this.satisfaction -= (this.taxes - 50) * 0.5;
        else if(this.taxes < 50) this.satisfaction += (50 - this.taxes) * 0.5;
        if(this.security > 50) this.satisfaction += (this.security - 50) * 0.5;
        else if(this.security < 50) this.satisfaction -= (50 - this.security) * 0.5;
        if(this.workSchedule > 50) this.satisfaction -= (this.workSchedule - 50) * 0.5;
        else if(this.workSchedule < 50) this.satisfaction += (50 - this.workSchedule) * 0.5;
        if(this.cleaning > 50) this.satisfaction += (this.cleaning - 50) * 0.5;
        else if(this.cleaning < 50) this.satisfaction -= (50 - this.cleaning) * 0.5;

        this.satisfaction = Math.max(0, Math.min(100, this.satisfaction));

    }
    //MONEY GENERATED AFFECTED BY DISTRICT PERCENTAGE 
    getMoneyGenerated() {
        const buildingsIncome = this.moneyGeneratedByBuildings.reduce((sum, income) => sum + income, 0);
        return this.moneyGenerated + buildingsIncome;
    }
    modifyDistrictMoneyGenerated(){
        // IF TAXES INCREASE, MONEY INCREASE. IF TAXES DECREASE, MONEY DECREASE
        // IF SECURITY INCREASE, MONEY DECREASE. IF SECURITY DECREASE, MONEY INCREASE
        // IF WORK SCHEDULE INCREASE, BUILDING MONEY INCREASE. IF WORK SCHEDULE DECREASE, BUILDING MONEY DECREASE
        // IF CLEANING INCREASE, MONEY DECREASE. IF CLEANING DECREASE, MONEY INCREASE
        this.moneyGenerated = this.baseMoneyGenerated;
        // clonar array para no mutar el original base directamente
        this.moneyGeneratedByBuildings = [...this.baseMoneyGeneratedByBuildings];

        if(this.taxes > 50) this.moneyGenerated += (this.taxes - 50) * 1000;
        else if(this.taxes < 50) this.moneyGenerated -= (50 - this.taxes) * 1000;
        if(this.security > 50) this.moneyGenerated -= (this.security - 50) * 1000;
        else if(this.security < 50) this.moneyGenerated += (50 - this.security) * 1000;

        this.moneyGeneratedByBuildings.forEach((income, idx) => {
            if(this.workSchedule > 50) {
                this.moneyGeneratedByBuildings[idx] = income + ((this.workSchedule - 50) / 100) * income;
            } else if(this.workSchedule < 50) {
                this.moneyGeneratedByBuildings[idx] = income - ((50 - this.workSchedule) / 100) * income;
            }
        });

        if(this.cleaning > 50) this.moneyGenerated -= (this.cleaning - 50) * 1000;
        else if(this.cleaning < 50) this.moneyGenerated += (50 - this.cleaning) * 1000;
    }

    //DISTRICT PERCENTAGE
    getTaxesPercentage() {return this.taxes;}
    getSecurityPercentage() {return this.security;}
    getWorkSchedulePercentage() {return this.workSchedule;}
    getCleaningPercentage() {return this.cleaning;}
    addTaxesPercentage(quantity){this.taxes = Math.max(0, Math.min(100, this.taxes + quantity));}
    addSecurityPercentage(quantity){this.security = Math.max(0, Math.min(100, this.security + quantity));}
    addWorkSchedulePercentage(quantity){this.workSchedule = Math.max(0, Math.min(100, this.workSchedule + quantity));}
    addCleaningPercentage(quantity){this.cleaning = Math.max(0, Math.min(100, this.cleaning + quantity));}
    //BUILDINGS
    getBuildingsList() {return this.district_building;}         
    getBuildingsBuilt() {return this.building_list;}
    getSpaceBuilding() {return this.space_building;}
    getSpaceBuildingBuilt() {return this.building_list.length;}
    isSpecialBuildingBuilt() {return this.is_special_built;}
    getSpecialBuilding() {throw new Error('createSceneList() debe implementarse en la subclase');}
    canBuildMore() {return this.building_list.length < this.space_building;}
    createBuildings(built,buildings){
        const buildingList = [];
        for(let i = 0 ; i < buildings.length; i++){
            //PNGBuilding,name,cost,income,satisfaction,populationIncrease
            if(buildings[i] === "CINEMA") buildingList.push(new BuildingCinema('buildingCinema',"CINEMA",10000,5000,5,100));
            else if(buildings[i] === "COMERCIAL") buildingList.push(new BuildingComercialCenter('buildingComercialCenter',"COMERCIAL",30000,20000,10,100));
            else if(buildings[i] === "FACTORY") buildingList.push(new BuildingFactory('buildingFactory',"FACTORY",50000,30000,-5,-1000));
            else if(buildings[i] === "HOSPITAL") buildingList.push(new BuildingHospital('buildingHospital',"HOSPITAL",60000,40000,5,1000));
            else if(buildings[i] === "HOTEL") buildingList.push(new BuildingHotel('buildingHotel',"HOTEL",20000,10000,5,500));
            else if(buildings[i] === "HOUSE") buildingList.push(new BuildingHouse('buildingHouse',"HOUSE",5000,500,5,200));
            else if(buildings[i] === "PARK") buildingList.push(new BuildingPark('buildingPark',"PARK",10000,1000,15,-100));
        }
        if(built) {
            for(let i = 0; i < buildingList.length; i++){
                const income = buildingList[i].getBuildingIncome();
                this.moneyGeneratedByBuildings.push(income);
                this.baseMoneyGeneratedByBuildings.push(income);
                this.updatePopulationIncrease(buildingList[i].getBuildingPopulationIncrease());
                this.updateSatisfaction(buildingList[i].getBuildingSatisfaction());
            }
        }
        return buildingList;
    }
    addBuilding(building) {
        if (this.district_building.includes(building)) {
            if(this.building_list.length < this.space_building){
                this.building_list.push(building);
                this.moneyGeneratedByBuildings.push(building.getBuildingIncome());
                this.baseMoneyGeneratedByBuildings.push(building.getBuildingIncome());
                this.updatePopulationIncrease(building.getBuildingPopulationIncrease());
                this.updateSatisfaction(building.getBuildingSatisfaction());
            }
            else{
                console.log("You can't add more buildings. No more space in the district.");
                throw new Error("No more space in the district.");
            }
        }else{
            console.log("This building doesn't exist in this district.");
            throw new Error("This building doesn't exist in this district.");
        }
    }
    addSpecialBuilding(building) {
        if (!this.is_special_built && this.special_building === building.getName()) {
            if(this.building_list.length < this.space_building){
                this.building_list.push(building); 
                this.is_special_built = true;
                this.moneyGeneratedByBuildings.push(building.getBuildingIncome());
                this.baseMoneyGeneratedByBuildings.push(building.getBuildingIncome());
                this.updatePopulationIncrease(building.getBuildingPopulationIncrease());
                this.updateSatisfaction(building.getBuildingSatisfaction());
            }
            else{
                console.log("You can't add more buildings. No more space in the district.");
                throw new Error("No more space in the district.");
            }
        }
        else{
            console.log("This building can't be built in this district.");
            throw new Error("This building can't be built in this district.");
        }
    }
}